# Generated by Django 5.1.6 on 2025-02-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRStockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendation_key', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_analyst_opinions', models.IntegerField(blank=True, null=True)),
                ('target_median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_mean_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_to_median', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_to_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_to_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_id', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('ticker', 'update_id')},
            },
        ),
        migrations.CreateModel(
            name='USAStockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendation_key', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_analyst_opinions', models.IntegerField(blank=True, null=True)),
                ('target_median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_mean_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_to_median', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_to_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_to_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_id', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('ticker', 'update_id')},
            },
        ),
    ]
