from marshmallow import Schema, fields

class FluxoDDMItemSchema(Schema):
    Data = fields.Str()
    Estrangeiro = fields.Str()
    Institucional = fields.Str()
    Pessoa_fisica = fields.Str(data_key="Pessoa física")
    Inst_Financeira = fields.Str(data_key="Inst. Financeira")
    Outros = fields.Str()
    Todos = fields.Str()

class FluxoDDMSchema(Schema):
    fluxo_ddm = fields.List(fields.Nested(FluxoDDMItemSchema))
    
class RRGDataItemSchema(Schema):
    Dates = fields.List(fields.Str())
    RS_Ratio = fields.List(fields.Float())
    RS_Momentum = fields.List(fields.Float())

class RRGDataSchema(Schema):
    PETR4 = fields.Nested(RRGDataItemSchema)
    VALE3 = fields.Nested(RRGDataItemSchema)
    BBAS3 = fields.Nested(RRGDataItemSchema)
    BBDC4 = fields.Nested(RRGDataItemSchema)
    COGN3 = fields.Nested(RRGDataItemSchema)
    MGLU3 = fields.Nested(RRGDataItemSchema)
    ITUB4 = fields.Nested(RRGDataItemSchema)
    WEGE3 = fields.Nested(RRGDataItemSchema)
    EMBR3 = fields.Nested(RRGDataItemSchema)

class CumulativePerformanceSchema(Schema):
    CDI = fields.Dict(keys=fields.Str(), values=fields.Float())
    SP500 = fields.Dict(keys=fields.Str(), values=fields.Float())
    Gold = fields.Dict(keys=fields.Str(), values=fields.Float())
    USDBRL = fields.Dict(keys=fields.Str(), values=fields.Float())
    IBOV = fields.Dict(keys=fields.Str(), values=fields.Float())

class VolatilityAnalysisSchema(Schema):
    symbol = fields.Str()
    open = fields.Float()
    high = fields.Float()
    low = fields.Float()
    close = fields.Float()
    variation = fields.Float()
    volume = fields.Int()
    financial_volume = fields.Float()
    ewma_1y_max = fields.Float()
    ewma_1y_min = fields.Float()
    ewma_1y_percentile = fields.Float()
    ewma_1y_rank = fields.Float()
    ewma_6m_max = fields.Float()
    ewma_6m_min = fields.Float()
    ewma_6m_percentile = fields.Float()
    ewma_6m_rank = fields.Float()
    ewma_current = fields.Float()
    iv_1y_max = fields.Float()
    iv_1y_min = fields.Float()
    iv_1y_percentile = fields.Float()
    iv_1y_rank = fields.Float()
    iv_6m_max = fields.Float()
    iv_6m_min = fields.Float()
    iv_6m_percentile = fields.Float()
    iv_6m_rank = fields.Float()
    iv_current = fields.Float()
    middle_term_trend = fields.Int()
    semi_return_1y = fields.Float()
    short_term_trend = fields.Int()
    beta_ibov = fields.Float()
    garch11_1y = fields.Float()
    correl_ibov = fields.Float()
    entropy = fields.Float()
    iv_to_ewma_ratio_1y = fields.Float()
    iv_to_ewma_ratio_6m = fields.Float()
    iv_to_ewma_ratio_current = fields.Float()

class IBOVSchema(Schema):
    symbol = fields.Str()
    type = fields.Str()
    name = fields.Str()
    open = fields.Float()
    high = fields.Float()
    low = fields.Float()
    close = fields.Float()
    volume = fields.Int()
    financial_volume = fields.Float()
    trades = fields.Int()
    bid = fields.Float()
    ask = fields.Float()
    category = fields.Str()
    contract_size = fields.Int()
    created_at = fields.Str()
    updated_at = fields.Str()
    variation = fields.Float()
    ewma_1y_max = fields.Float()
    ewma_1y_min = fields.Float()
    ewma_1y_percentile = fields.Float()
    ewma_1y_rank = fields.Float()
    ewma_6m_max = fields.Float()
    ewma_6m_min = fields.Float()
    ewma_6m_percentile = fields.Float()
    ewma_6m_rank = fields.Float()
    ewma_current = fields.Float()
    has_options = fields.Bool()
    iv_1y_max = fields.Float()
    iv_1y_min = fields.Float()
    iv_1y_percentile = fields.Float()
    iv_1y_rank = fields.Float()
    iv_6m_max = fields.Float()
    iv_6m_min = fields.Float()
    iv_6m_percentile = fields.Float()
    iv_6m_rank = fields.Float()
    iv_current = fields.Float()
    middle_term_trend = fields.Int()
    semi_return_1y = fields.Float()
    short_term_trend = fields.Int()
    stdv_1y = fields.Float()
    stdv_5d = fields.Float()
    beta_ibov = fields.Float()
    garch11_1y = fields.Float()
    isin = fields.Str()
    correl_ibov = fields.Float()
    entropy = fields.Float()
    sector = fields.Str()
    cvmCode = fields.Str(allow_none=True)
    currency = fields.Str(allow_none=True)
    currencyScale = fields.Int(allow_none=True)
    marketMaker = fields.Bool(allow_none=True)
    previousClose = fields.Float(allow_none=True)
    time = fields.Str()




